# Nombre de tu aplicación
spring.application.name=modulo-reservas

# ⚠️ Dirección IP de tu Broker de Kafka en Azure
spring.kafka.bootstrap-servers=20.186.91.190:9092

# Configuración del Consumidor (Módulo de Inventario -> Reservas)
spring.kafka.consumer.group-id=grupo-modulo-reservas
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Configuración del Productor (Reservas -> Facturación)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
# Configuración de la Base de Datos
# 💾 Configuración Correcta para NeonDB en Spring Boot
spring.datasource.url=jdbc:postgresql://ep-misty-hall-atly3o4p-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=prefer&gssencmode=disable
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Eab4jKD5oJhg
spring.datasource.driver-class-name=org.postgresql.Driver